name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build static library with Docker image
      run: docker build -t template . && docker run -v "$(pwd):/app" template
      
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust Nightly       
      run: rustup override set nightly
    - name: Build
      run: make build
    - name: Build micro
      run: make build_micro
    - name: Run tests
      run: make test
    - name: Run benchmark
      run : make bench
